### ISSUE TITLE
Incorrect mutation PDB

### ISSUE THREAD

**Issue by JinyuanSun** [gersteinlab/ThermoNet#9]
This file `data/pdbs/s_sym/1lz1A/1lz1A_relaxed_C77A_relaxed.pdb` dose not have the desired C77A mutation.
<img width="774" alt="image" src="https://github.com/gersteinlab/ThermoNet/assets/33344948/5e83eaa5-17b7-48e1-b9d7-e89ed0fd68f7">

**Comment by computbiolgeek** [comment]
Hi Jinyuan, thanks for reporting this error in the PDB file. I suspect what happened was that because C77 is part of a disulfide bond specified at the top of the wild-type PDB file, this specification of disulfide bond overrides the C77A mutation in the resfile when the FastRelax protocol was used to make the mutant structure. However, I did not verify this suspicion. So, I could be wrong. 

In any case, as stated in the paper Rosetta generated mutant structures weren't used in voxelization for the S_Sym dataset because experimental structures for all mutations of the S_Sym dataset were available in the PDB. So, for S_Sym, mutant structures from the PDB were Rosetta relaxed and aligned to the respective wild-type structure before voxelization.

**Comment by JinyuanSun** [comment]
I see. Thanks! I will use the PDB structure in the S_Sym dataset.
